---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.labeljob}}
  namespace: {{.Values.namespace}}
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: {{.Values.labeljob}}
        image: 529396670287.dkr.ecr.us-west-2.amazonaws.com/trogaev-ecr-backend-dacpack:v3
        env:
        - name: TargetServerName
          value: myapp-mssql-service.deploy
        - name: TargetDatabaseName
          value: WeeklyReport
        - name: TargetUser
          value: sa
        - name: TargetPassword
          value: Password.
        ports:
        - containerPort: 1433
      restartPolicy: Never

